### ISSUE TITLE
Cannot install R package

### ISSUE THREAD

**Issue by dfermin** [davidaknowles/leafcutter#119]
Hi

I'm trying to install the latest release of leafcutter but consistently fail to install the R package.
I've installed RStan 2.19.2 without any problems. And all the dependencies.

But the recommended method doesn't work.
I tried: `devtools::install_github("davidaknowles/leafcutter/leafcutter")`

And I get this error:
```
* installing *source* package ‘leafcutter’ ...
** libs
Error in .shlib_internal(args) :
  C++14 standard requested but CXX14 is not defined
* removing ‘/opt/microsoft/ropen/3.5.3/lib64/R/library/leafcutter’
Error: Failed to install 'leafcutter' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpKx5Yb3/fileb659745e167e/leafcutter_0.2.8.tar.gz’ had non-zero exit status

```
Here is my session info:
```
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Workstation 7.7 (Maipo)

Matrix products: default
BLAS: /opt/microsoft/ropen/3.5.3/lib64/R/lib/libRblas.so
LAPACK: /opt/microsoft/ropen/3.5.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] RevoUtils_11.0.3     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        magrittr_1.5      usethis_1.5.1     devtools_2.2.1
 [5] pkgload_1.0.2     R6_2.4.0          rlang_0.4.1       tools_3.5.3
 [9] pkgbuild_1.0.6    sessioninfo_1.1.1 cli_1.1.0         withr_2.1.2
[13] ellipsis_0.3.0    remotes_2.1.0     assertthat_0.2.1  digest_0.6.22
[17] rprojroot_1.3-2   crayon_1.3.4      processx_3.4.1    callr_3.3.2
[21] fs_1.3.1          ps_1.3.0          curl_4.2          testthat_2.3.0
[25] memoise_1.1.0     glue_1.3.1        compiler_3.5.3    desc_1.2.0
[29] backports_1.1.5   prettyunits_1.0.2
```

I'm running CentOS 7.7
Any suggestions?

Thanks

**Comment by jackhump** [comment]
This works for me on R 3.6.0:

```
devtools::install_github("stan-dev/rstantools")
devtools::install_github("davidaknowles/leafcutter/leafcutter", ref = "stanfixagain")
```

**Comment by CancerGenome** [comment]
Also works for me on R 3.6.1

**Comment by skytguuu** [comment]
not work for me on R 3.6.0, R 3.6.1 and R 3.5.3.

Any help? It is so hard to install this package.

**Comment by jackhump** [comment]
@skytguuu can you give more information on your setup? What have you tried so far?

**Comment by skytguuu** [comment]
Thanks for your help. I tried installed in my windows, but it still report the "non-zero status" error. So, I changed to my linux. 
I also have other questions about "leafcutter". Because I tried to analyze the alternative splicing in time curse events (In each time, there are only two replicates, I am not sure it is enough or not). In the tutorial, you said this tool only support two groups. Because my data have only two replicates in each time, could I compare two group by two different time with “leafcutter”? Are those two replicates enough to find the differential intron excision analysis? 
Another question is about the step 2. In the step 2 result, we had got the splicing events in the intron, could I use this result to count the number of alternative splicing in each replicates with custermor code? Then use such limma to find the different splicing? Could you give some advises?

Thanks!
Best,
Garen

**Comment by jackhump** [comment]
Dear Garen,

Did you manage to install Leafcutter on Linux? We don't have much experience with installing it on Windows, only Mac and Linux.

You're correct that Leafcutter only compares splicing between two groups, so you will have to perform multiple passes to compare your four different groups.
I'm not sure I understand your second question though. The Differential Splicing step gives you a set of clusters that are differentially spliced between your two groups. The counts of each junction for each sample are in the perind_numers.counts.gz file created by the clustering step.

**Comment by skytguuu** [comment]
I have tried on Ubuntu 18.04. It worked now. Thanks.
In the second question, I was wondering that could I just the the result of step 2 to divide the splicing into different types (such as alternative 5' splicing).

Thanks

**Comment by jackhump** [comment]
See here: #120

**Comment by skytguuu** [comment]
Thanks, I met another problem. Because I have only two replicates in each sample, so if I used default parameters to run step 3(Differential intron excision analysis). It reported the error (need to set --min_samples_per_intron). It still failed even I set the min_samples_per_intron with 2). Could you give me a hand?

Thanks

**Comment by jackhump** [comment]
Can you paste in the error message?

**Comment by aa-nava** [comment]
@dfermin we were also never able to successfully install/test leafcutter on Linux server using any of the instructions published on leafcutter's github, I would recommend selecting a different software like MAJIQ from UPenn since it has more extensive documentation and was easily installed within a day.
