### ISSUE TITLE
Leafviz annotation caveats

### ISSUE THREAD

**Issue by gungne** [davidaknowles/leafcutter#48]
Gtf files from ensembl usually only has chromosome number as in the chromosome column. 

It seems the prepare_results.R only works with "chr" implemented annotation. 

If I use directly from original ensembl gtf, it will popup this error message:

Error in left_join_impl(x, y, by$x, by$y, suffix$x, suffix$y, check_na_matches(na_matches)) : 
  Can't join on 'chr' x 'chr' because of incompatible types (integer / character)
Calls: %>% ... left_join -> left_join.tbl_df -> left_join_impl -> .Call
Execution halted

**Comment by jackhump** [comment]
Hi, I've submitted a bug fix to this: #49

**Comment by jackhump** [comment]
Dear @gungne, I've merged this bug fix. Could you verify that this fixes your problem?

**Comment by LittleFrogHill** [comment]
I can get leafviz.RData，but there is a probl
![image](https://user-images.githubusercontent.com/34407101/38767740-bea0102a-4019-11e8-825c-d356361687ac.png)
em on the last step I doubt it's because of the GTF file either.

**Comment by jackhump** [comment]
Hi LittleFrogHill, sorry to hear that. Can you confirm that all your clusters have the same error message?

When you ran prepare_results.R, were there any error messages then?

**Comment by LittleFrogHill** [comment]
Hi，Jack，I had check many clusters they all have this problem，and sometimes the gene below also cannot display.


There is no error when I ran prepare_results.R.
Thank you for answering.


| |
邮箱：gaoshan30954@163.com
|

签名由 网易邮箱大师 定制

On 04/14/2018 19:35, Jack Humphrey wrote:

Hi LittleFrogHill, sorry to hear that. Can you confirm that all your clusters have the same error message?

When you ran prepare_results.R, were there any error messages then?

**Comment by jackhump** [comment]
That is curious.
Would you mind sending me the Rdata file produced by prepare_data.Rdata?
I can have a look at what might be the problem. We need to build more tests into the code to stop these weird bugs from happening.

On 14 Apr 2018 12:57 pm, LittleFrogHill <notifications@github.com> wrote:
Hi，Jack，I had check many clusters they all have this problem，and sometimes the gene below also cannot display.


There is no error when I ran prepare_results.R.
Thank you for answering.


| |
邮箱：gaoshan30954@163.com
|

签名由 网易邮箱大师 定制

On 04/14/2018 19:35, Jack Humphrey wrote:

Hi LittleFrogHill, sorry to hear that. Can you confirm that all your clusters have the same error message?

When you ran prepare_results.R, were there any error messages then?

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

―

**Comment by LittleFrogHill** [comment]
Excellent，but I‘m out of office.I will send you as soon as possible.
Thanks.


| |
邮箱：gaoshan30954@163.com
|

签名由 网易邮箱大师 定制

On 04/14/2018 20:48, Jack Humphrey wrote:
That is curious.
Would you mind sending me the Rdata file produced by prepare_data.Rdata?
I can have a look at what might be the problem. We need to build more tests into the code to stop these weird bugs from happening.

On 14 Apr 2018 12:57 pm, LittleFrogHill <notifications@github.com> wrote:
Hi，Jack，I had check many clusters they all have this problem，and sometimes the gene below also cannot display.


There is no error when I ran prepare_results.R.
Thank you for answering.


| |
邮箱：gaoshan30954@163.com
|

签名由 网易邮箱大师 定制

On 04/14/2018 19:35, Jack Humphrey wrote:

Hi LittleFrogHill, sorry to hear that. Can you confirm that all your clusters have the same error message?

When you ran prepare_results.R, were there any error messages then?

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

―

**Comment by LittleFrogHill** [comment]
I add 'chr' in my GTF file ,and some genes' results are OK.But still some can't display the picture in Firefox.
And when I run the prepare_results.R,there are some Warning messages:
I have no idea if these warning result or the speices I choese(horse,annotation is not as good as human) result the problem.


高山
陕西省杨凌区西北农林科技大学712100
Shan Gao 
Laboratory for Genomic Big Data
College of Animal Science and Technology
Northwest A&F University
Yangling, Shaanxi, 712100, China 




On 4/14/2018 20:48，Jack Humphrey<notifications@github.com> wrote：
That is curious.
Would you mind sending me the Rdata file produced by prepare_data.Rdata?
I can have a look at what might be the problem. We need to build more tests into the code to stop these weird bugs from happening.

On 14 Apr 2018 12:57 pm, LittleFrogHill <notifications@github.com> wrote:
Hi，Jack，I had check many clusters they all have this problem，and sometimes the gene below also cannot display.


There is no error when I ran prepare_results.R.
Thank you for answering.


| |
邮箱：gaoshan30954@163.com
|

签名由 网易邮箱大师 定制

On 04/14/2018 19:35, Jack Humphrey wrote:

Hi LittleFrogHill, sorry to hear that. Can you confirm that all your clusters have the same error message?

When you ran prepare_results.R, were there any error messages then?

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

―

**Comment by jackhump** [comment]
as discussed privately, these issues are due to incomplete annotation of the user's chosen species (horse).
