### ISSUE TITLE
+ and - clusters

### ISSUE THREAD

**Issue by eatsai** [davidaknowles/leafcutter#60]
Hi,
Thank you for building leafcutter! The results look promising, but it is puzzling to us why there are two distinct clusters for the same splicing event. When we stepped through the code, we realized that the '+' and '-' suffix on each cluster seemed to be indicating reads mapped on the forward or reverse strands.

Our question is:
If our RNA-sequencing isn't performed on a stranded kit, is there some way to disable the strandedness and have these identified clusters be "merged"?

Thanks,
Ellen

**Comment by goldenflaw** [comment]
Hi Ellen,

The strand is determined not by the the protocol, but by the inferred
intron junction strand. The "correct" strand should have the read mapped
like <read5'>GT---AG<read3'>.

Best,
Yang

**Comment by eatsai** [comment]
Hi Yang,
Thank you for your explanation.
1. What is the intuition for having clusters '+' and '-' describing the same splice junction?
2. Is there any way to combine the observations together into one cluster?

Regards,
Ellen

**Comment by goldenflaw** [comment]
Hi Ellen,

There shouldn't be many introns with both + and -'s. Is this what you
observe?

Yang

**Comment by atasub** [comment]
Hi there,
I have the same problem too.

I am having different q values for the same splicing events, which have been though indicated by different cluster ids, they are specifying the same splicing events.

For instance,

I got two significant clusters (+/-) such:

chr17:45962470:45969165:clu_29213_+ 5 2 3 2 3 1 1 1 1 1 4 2 2 1 2 1 3 3 2 8 3 2 1 0 2 5 3
chr17:45962470:45971859:clu_29213_+ 293 140 204 105 153 78 123 159 188 116 184 219 145 94 125 111 128 94 115 144 96 112 18 31 80 142 138
chr17:45962470:45978375:clu_29213_+ 203 147 151 105 97 149 122 99 111 126 142 219 133 90 102 145 117 176 80 120 143 140 138 99 86 131 138
chr17:45969299:45971859:clu_29213_+ 3 5 5 0 3 0 1 3 1 1 5 3 2 1 1 4 4 6 0 1 0 2 3 1 0 5 2
chr17:45971945:45974385:clu_29213_+ 31 27 13 6 11 3 16 21 25 13 30 20 17 9 17 12 2 12 14 10 18 12 1 5 8 8 16
chr17:45971945:45978375:clu_29213_+ 206 183 182 128 187 83 133 164 145 158 148 242 149 113 151 133 109 153 130 118 86 137 24 32 75 138 121
chr17:45974471:45978375:clu_29213_+ 19 26 25 14 19 11 20 20 27 18 33 23 15 20 12 17 16 9 14 10 11 10 0 3 6 16 20


chr17:45962470:45969165:clu_34802_- 5 3 6 0 7 5 1 1 6 2 5 5 2 3 2 5 3 1 4 5 6 1 3 3 3 5 3
chr17:45962470:45971859:clu_34802_- 226 113 160 78 131 72 89 113 145 125 160 150 153 81 133 96 113 131 104 119 81 88 10 29 68 126 113
chr17:45962470:45978375:clu_34802_- 193 130 103 109 123 155 112 101 86 144 118 213 142 101 101 170 98 202 107 122 187 159 150 98 82 148 99
chr17:45969299:45971859:clu_34802_- 4 5 0 0 3 0 0 0 0 3 4 0 0 0 4 2 2 2 0 2 2 1 0 1 1 1 2
chr17:45971945:45974385:clu_34802_- 34 21 19 6 11 8 17 12 23 11 34 18 11 15 16 14 4 1 7 5 13 12 1 5 7 12 13
chr17:45971945:45978375:clu_34802_- 258 100 172 93 146 71 92 118 175 117 148 171 125 80 126 113 113 99 102 109 111 105 20 30 79 139 118
chr17:45974471:45978375:clu_34802_- 25 18 11 7 22 5 18 24 19 14 30 17 16 15 13 14 15 9 13 11 14 7 0 4 13 7 17

When I checked the total number of - and + clusters, I found that 109692 "+" and 96140  "-" clusters. So, there is a high number of + and - indicated clusters.

If you can help me to figure out the problem, I would be glad.

Burcu

**Comment by goldenflaw** [comment]
Are you both using the bam2junc.sh script to convert your bam to
junction? I believe that there is a bug in this script which does not
correctly assign the strand. We are in the process of moving away from
bam2junc.sh and replacing it by the junctions extract function from
regtools (https://regtools.readthedocs.io/en/latest/commands/junctions-extract/).
If you really want strand right now, you can use that to extract your
junctions, and use scripts/leafcutter_cluster_regtools.py.

Otherwise, I have updated the leafcutter_cluster.py script to disable
the use of strand info by default. Please use git pull and re-run the
leafcutter_cluster.py step.

Sorry for this, and hope to update leafcutter soon.

Best,
Yang

**Comment by smshuai** [comment]
Hi Yang,

I have the same issue and I tried `regtools` out. I still have the following questions:
1. What parameters should I use for junction extraction with`regtools`? It seems that the `regtools` uses all reads instead of uniquely mapped reads.
2. The cluster name format returned by `scripts/leafcutter_cluster_regtools.py`seems to be incorrect. One example is "chrX:200700:200834:clu_2:-", but the `get_intron_meta` function only takes format like "chrX:200700:200834:clu_2_-".

Shimin

**Comment by goldenflaw** [comment]
Thanks Shimin,

I've now updated the cluster name format. Regarding regtools junction using
all reads, I don't see any options that controls the use of uniquely mapped
reads, my advice is to use samtools to filter all reads that you do not
want and then use regtools for junction extraction. Hope this solution will
work.

Best,
Yang

**Comment by eatsai** [comment]
Thanks Yang. I believe this fixes my issue. -E
