### ISSUE TITLE
LeafViz Gene-level vizualization: Error: Aesthetics must be either length 1

### ISSUE THREAD

**Issue by drevansa** [davidaknowles/leafcutter#65]
Re: Error: Aesthetics must be either length 1 or the same as the data (1): x, y, xend, yend, group, size

This issue appears to be down to annotation/ synonyms:
For LVRN for example, where the gene symbol given in leafcutter_ds_cluster_significance.txt
for the same cluster is: AQPEP
I've used your suggested gencode annotation files.

If you need any more information let me know.

**Comment by davidaknowles** [comment]
@jackhump any ideas? 

Do you know what line this is happening on?

**Comment by davidaknowles** [comment]
Fixed! To prove it: 
![image](https://user-images.githubusercontent.com/4521734/47401679-2a50ba80-d6f7-11e8-8ee3-b7fe8bb7c727.png)
The issue was if there were no significant clusters on one side it was trying to ggplot an empty data.frame. Adding some logic to check for that and cleaned up the code some. The fix requires a reinstall since `make_gene_plot` has changed.

**Comment by drevansa** [comment]
Thank you!  Also, thank you very much for uploading my final missing plot - I'm mid projects at the moment so can't do a leafcutter reinstall at the moment.

**Comment by davidaknowles** [comment]
No worries and sorry it took so long. Going on the job market wasn't very conducive to finding time to fix bugs!
