### ISSUE TITLE
ambiguous annotation for brain samples' data

### ISSUE THREAD

**Issue by atasub** [davidaknowles/leafcutter#69]
Hi there,
When I ran Lafcutter to analyze brain samples' data, I received this AS for the "MAPT" gene: 
![image](https://user-images.githubusercontent.com/26298242/40415676-c3057df0-5e7b-11e8-9368-87059cde18cf.png)

However, as I know that exon 8 of the MAPT gene is not expressed in brain, I could not figure out, how it could be possible to get significant AS events for that region covering exon 8. This is the UCSC view:

<img width="1280" alt="screen shot 2018-05-23 at 11 38 26" src="https://user-images.githubusercontent.com/26298242/40416624-0467503c-5e7e-11e8-982e-5f45a8525634.png">
In this case, do I need to take into consideration the canonical transcript or the other transcripts as well?  So, if you can help me to interpret this result, I would be glad. 

Thanks..

Burcu

**Comment by jackhump** [comment]
Dear Burcu,

I assume you ran the LeafViz analysis using the GENCODE hg38 annotation we provide. This is the comprehensive list of all human transcripts discovered by both HAVANA and Ensembl. LeafViz uses this to assign each junction in each cluster to a known transcript if it exists. Otherwise they are labelled as "cryptic". So even transcripts that you believe shouldn't be expressed will be annotated if there are any junctions present.

You are correct that exon 8 is not expressed in your samples - it is 96-98% excluded. The cluster you see there has a very small number of junctions that corresponding to inclusion and the p-value is not very impressive  I wouldn't worry too much. Does that make sense?

**Comment by jackhump** [comment]
I determined that by looking at the LeafViz splicing event visualisation - in your cases, on average 95% of junctions in the cluster are those that skip the central exon, and in controls it is 98%. That means that your cases have a 2% decrease in exon skipping. Now is that biologically relevant? Probably not. But the junctions exist.

I think you could comfortably increase your minimum reads per cluster but I'm not sure it would help in this case.

**Comment by jackhump** [comment]
If you want to further discuss how to interpret these kind of events, let's continue this on the google group:  https://groups.google.com/forum/#!forum/leafcutter-users
