### ISSUE TITLE
namespace Rcpp is imported by [various packag es] so cannot be unloaded

### ISSUE THREAD

**Issue by pcarbo** [davidaknowles/leafcutter#72]
@davidaknowles We reproduced this error on two different machines when trying to load your package after installing it:

```
library
 Package ‘Rcpp’ version 0.12.15 cannot be unloaded:
Error in unloadNamespace(package) : namespace ‘Rcpp’ is imported by ‘tidyr’, ‘scales’, ‘edgeR’, ‘plyr’, ‘htmltools’, ‘reshape2’, ‘tidyselect’ so cannot be unloaded
```

It is large to tell exactly why this issue is occurring---it may be a quirk in the `devtools::install` procedure---but a simple solution is to restart R before running `library(leafcutter)`. Maybe you should add this to your installation instructions since it seems that it could reoccur?

**Comment by nguinasso** [comment]
I had this problem too. 

It turned out that I had lines in my .Rprofile that loaded lubridate into the Namespace.  This was causing RStudio to fail the Check of a package with an error in unix.  

I removed those lines in .Rprofile and the packaged built without problems. 

The same package did not have this problem in Windows  .

**Comment by davidaknowles** [comment]
Thanks I've added a note about this to the docs.
