### ISSUE TITLE
cell-type specific Intron excision ratios 

### ISSUE THREAD

**Issue by gouthamatla** [davidaknowles/leafcutter#93]
Hi,

I want to classify cell-type specific intron excision events. I have only one sample per cell-type, 4 cell-types in total, so I can not do differential splicing analysis. Do you have any suggestions on how could I check if intron-excision ratios are cell-type specific ?

Is it valid approach to normalize the values in `_perind_numers.counts.gz` to the total number of counts in samples ( like a TPM approach), 
For example, if my library sizes (total number of reads supporting splice junctions/colSums) are 22,000,000 34,000,000 55,000,000 87,000,000

Then:
```
chr2:280149:283111:clu_7_NA    0    2    2    437
chr2:280152:283111:clu_7_NA    2    0    13   505
```
after per million seq-depth normalisation, it will be:
```
chr2:280149:283111:clu_7_NA    0.04    0.05    0.036    5.02
chr2:280152:283111:clu_7_NA    0.09    0.02    0.23    5.80
```
Then I could calculate a Z-score per cell-type or a clustering approach ?

**Comment by davidaknowles** [comment]
The problem with this is you would confound splicing and expression, which is why you want to normalize within some relevant unit (i.e. gene or leafcutter splicing cluster). 
You can run 1 vs 1 DS analysis with leafcutter if you set `-g 1` and `-i 1`... just don't put too much faith in the `p`-values you get!
